# Generated by Django 4.2.7 on 2023-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnxt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='tmdb', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='image_url',
            field=models.CharField(default='tmdb', max_length=200, null=True),
        ),
    ]
