# Generated by Django 4.2.7 on 2023-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upnxt', '0003_alter_review_movie_alter_review_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
